// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMusic.Data;

#nullable disable

namespace WebMusic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220520172143_add_imageid_album")]
    partial class add_imageid_album
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebMusic.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BandaId")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("WebMusic.Models.Banda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Bandas");
                });

            modelBuilder.Entity("WebMusic.Models.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cancions");
                });

            modelBuilder.Entity("WebMusic.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("des_genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("des_genero")
                        .IsUnique();

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("WebMusic.Models.Album", b =>
                {
                    b.HasOne("WebMusic.Models.Banda", null)
                        .WithMany("Albums")
                        .HasForeignKey("BandaId");
                });

            modelBuilder.Entity("WebMusic.Models.Banda", b =>
                {
                    b.HasOne("WebMusic.Models.Genero", null)
                        .WithMany("Bandas")
                        .HasForeignKey("GeneroId");
                });

            modelBuilder.Entity("WebMusic.Models.Cancion", b =>
                {
                    b.HasOne("WebMusic.Models.Album", null)
                        .WithMany("Cancions")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("WebMusic.Models.Album", b =>
                {
                    b.Navigation("Cancions");
                });

            modelBuilder.Entity("WebMusic.Models.Banda", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("WebMusic.Models.Genero", b =>
                {
                    b.Navigation("Bandas");
                });
#pragma warning restore 612, 618
        }
    }
}
